name: dart_service_logger
description: Provide implementation of dart_logging_abstraction package using logger and support dart_service_provider extensions.
version: 1.0.0
repository: https://github.com/codelovercc/dart_service_logger

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dart_logging_abstraction: ^1.1.0
  dart_service_provider: ^1.1.0
  logger: ^2.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
